version: '3.1'

services:

  db:
    image: postgres
    container_name: minimalistdb
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: minimalist_db
